### ISSUE TITLE
libiso15118: TLS 1.3 EOF error while performing handshake with libiso15118

### ISSUE THREAD

**Issue by FaHaGit** [EVerest/everest-core#574]
**Environment:**
everest-core:
https://github.com/EVerest/everest-core/commit/3e5c467546ddfb3341083480ced7e01b0786e92c
libiso15118:
https://github.com/EVerest/libiso15118/commit/0f34d53737606ab5de783858c06a80521f3a5710

EV: Trialog Testsystem

**Test Sequence:**

- Start of TLS 1.3 session

**Expected Behavior:**

TLS handshake runs through and v2g communication starts

**Observed Behavior:**

TLS handshake fails with error message 1:

Feb 01 10:58:57 tarragon01 manager[20097]: 2024-02-01 10:58:57.484532 [INFO] connector_1:Evs  :: EVSE ISO SLAC MATCHED
Feb 01 10:58:57 tarragon01 manager[20097]: 2024-02-01 10:58:57.517753 [INFO] connector_1:Evs  :: EVSE ISO D-LINK_READY (true)
Feb 01 10:59:03 tarragon01 manager[20097]: 2024-02-01 10:59:03.906353 [INFO] connector_1:Evs  :: EVSE ISO Change HLC Limits: 11040W/200A, target_voltage 0, actual_voltage 2, hack_bpt false
Feb 01 10:59:05 tarragon01 manager[20097]: 2024-02-01 10:59:05.342393 [INFO] connector_1:Evs  :: EVSE ISO Change HLC Limits: 11040W/200A, target_voltage 0, actual_voltage 0, hack_bpt false
Feb 01 10:59:05 tarragon01 manager[20105]: 2024-02-01 10:59:05.833929 [INFO] iso15118_charge  :: Got SDP request
Feb 01 10:59:06 tarragon01 manager[20105]: 2024-02-01 10:59:06.864023 [ERRO] iso15118_charge virtual void module::charger::ISO15118_chargerImpl::ready() :: D20Evse chrashed: Failed to mbedtls_ssl_handshake() (SSL - The connection indicated an EOF)
Feb 01 10:59:06 tarragon01 manager[20105]: 2024-02-01 10:59:06.864738 [INFO] iso15118_charge  :: Shutting down SDP server!

TLS handshake fails with error message 2:

Feb 01 10:58:23 tarragon01 manager[12619]: 2024-02-01 10:58:23.580968 [INFO] connector_1:Evs  :: EVSE ISO SLAC MATCHED
Feb 01 10:58:23 tarragon01 manager[12619]: 2024-02-01 10:58:23.604079 [INFO] connector_1:Evs  :: EVSE ISO D-LINK_READY (true)
Feb 01 10:58:29 tarragon01 manager[12626]: 2024-02-01 10:58:29.900146 [INFO] iso15118_charge  :: Got SDP request
Feb 01 10:58:29 tarragon01 manager[12626]: 2024-02-01 10:58:29.912135 [ERRO] iso15118_charge virtual void module::charger::ISO15118_chargerImpl::ready() :: D20Evse chrashed: Failed to mbedtls_net_bind() (NET - Binding of the socket failed)
Feb 01 10:58:29 tarragon01 manager[12626]: 2024-02-01 10:58:29.919936 [INFO] iso15118_charge  :: Shutting down SDP

**Additional note:**
- because of data privacy it is not possible to add traces (recorded on testing symposium in Arnhem January 2024)
- Cipher Suite: TLS_AES_256_GCM_SHA384
- in pcap trace EV terminates the connection [FIN, ACK]
- error message 2 occurs only sporadically
- module crashes with a SEG-fault (Module iso15118_charger exited with status: 11. Terminating all modules)

**Comment by SebaLukas** [comment]
Without further information via trace or a non-existent trialog tester, I cannot reproduce the problem and debug it accordingly.
However, I will test again with Josev (TLS 1.3) in the next few days. However, I suspect that TLS 1.3 is still working in libiso15118.

Based on my experience over the last few months, I suspect that the tester is the problem.

**Comment by SebaLukas** [comment]
You are right with the segfault. This should not happen after a failed tls handshake. Please reopen this issue in the libiso15118 repo.
