### ISSUE TITLE
0 kW power delivered while in the Charging phase

### ISSUE THREAD

**Issue by sahabulh** [EVerest/everest-core#645]
### Describe the bug

US-JOET and the Sandia team are developing one-liner demos in [everest-demo](https://github.com/EVerest/everest-demo). We were able to run an `AC ISO15118-2 PnC` charging session using MaEVe as the CSMS. Everything works fine except for the fact that while in the Charging phase in the GUI, it shows `0 kW` power being delivered. Please check the attached screenshot. In other modes (i.e., `AC 3ph 16A`), it works as expected. We were told that it is a known problem so I am submitting an issue against it.

AC 15118-2 PnC:
![Screenshot from 2024-04-22 11-39-21](https://github.com/EVerest/everest-core/assets/43827957/96f0c6c4-de53-417f-8526-82b8c19052f9)

AC 3ph 16A:
![Screenshot from 2024-04-22 11-39-51](https://github.com/EVerest/everest-core/assets/43827957/c82ac891-2b72-459b-9b43-0a569f00121f)

### EVerest Domain

Energy Management, ISO15118, Simulation

### To Reproduce

Use [this version](https://github.com/EVerest/everest-demo/tree/dc6b53c7ae1db7ca1631ccd575183694b41a4061) and the `Basic and ISO 15118-2 AC Charging with OCPP 2.0.1 CSMS (MaEVe Security Profile 3)` one-liner to reproduce.

**Comment by SebaLukas** [comment]
Fix for this issue is merged
