### ISSUE TITLE
python3 -m pip install --upgrade pip setuptools wheel jstyleson jsonschema error.

### ISSUE THREAD

**Issue by Elsa-is-My-Muse** [EVerest/everest-core#663]
### Describe the bug

![image](https://github.com/EVerest/everest-core/assets/168414969/b2e09698-b865-4ea9-ad68-d46557382c19)
![image](https://github.com/EVerest/everest-core/assets/168414969/85e5b91c-b423-40b9-bf99-81146898a8a1)

### EVerest Domain

Other

**Comment by krealyt** [comment]
I would install that missing package manually.

**Comment by krealyt** [comment]
Checking if something in the install process can be improved.

Anyone a fast additional idea / opinion on that?
