### ISSUE TITLE
Active errors are not cleared in API module

### ISSUE THREAD

**Issue by marco-mariotto** [EVerest/everest-core#797]
### Describe the bug

In the API.cpp file when a non-permanent error gets cleared, shouldn't we have the following:
```
    case Event::ErrorCleared:
        remove_error_from_list(this->active_errors, error.type);
        break;
``` 
Currently it just falls back to `case Event::PermanentFaultCleared`

### EVerest Domain

Other

### Affected EVerest Module

API.cpp, function `SessionInfo::update_state`

### To Reproduce

Version is tag 2024.6.0.

**Comment by Pietfried** [comment]
The `PermanentFaultCleared` event has been removed from the `evse_manager` types and the API module now makes use of the [error handling provided by the everest-framework](https://everest.github.io/nightly/general/01_framework/error_framework.html#error-framework)
