### ISSUE TITLE
EvseManager: `allow_power_on(false)` gets called repeatedly while error active

### ISSUE THREAD

**Issue by a-w50** [EVerest/everest-core#829]
### Describe the bug

Given, that
-  the `EvseManager` is in state `PrepareCharging`
- and an error gets raised, which prevents charging

then, the `EvseManager` continuously calls `allow_power_on(false)`, due to this function:
```
bool Charger::errors_prevent_charging_internal() {
    if (shared_context.error_prevent_charging_flag) {
        graceful_stop_charging();
        return true;
    }
    return false;
}
```
(Note, the name and signature of this function suggests, that it only checks something - but it has *side-effects*, i.e. `graceful_stop_charging()`)

I would expect that `allow_power_on(false)` gets called only as long as the bsp event `PowerOff` hasn't been received and probably at a lower rate (`MAINLOOP_UPDATE_RATE` = 100ms right now).

### EVerest Domain

Charge Control

### Affected EVerest Module

EvseManager

### To Reproduce

Get the `EvseManager` into state `PrepareCharging` and raise a `VendorError` from the `board_support` module.

**Comment by dev-enphase** [comment]
Is there any traction on this issue? Please fix this issue ASAP as this is causing performance issue in the system

**Comment by dev-enphase** [comment]
[like]  Devendra Chouhan reacted to your message:
________________________________
