### ISSUE TITLE
Node version error for Node-red UI table for nodered-sil.sh script

### ISSUE THREAD

**Issue by luxscious** [EVerest/everest-core#922]
### Describe the bug

I tried to follow the tutorial for getting setup on everest quickly (I followed this a couple of months ago with success), but I'm encountering errors with the nodered-sil.sh script. I believe the new version of node-red needs Node version >=16 however the docker image that this script is pulling from uses version ~14. 

<img width="570" alt="image" src="https://github.com/user-attachments/assets/af4385e2-2d00-4c81-a859-d97320590a32">

Basically, the ui-table element is non-usable which breaks the node-red ui entirely. 

### EVerest Domain

Simulation

### Affected EVerest Module

docker image: everest-nodered

script: /everest/everest-core/build/run-scripts/nodered-sil.sh

### To Reproduce

follow the instructions to get setup on everest: (https://everest.github.io/latest/general/03_quick_start_guide.html)
This happens when running:
{EVerest Workspace Directory}/everest-core/build/run-scripts/nodered-sil.sh

### Anything else?

I believe you just need to update the Node version in the docker image as the ui table works fine for the other nodered image.

**Comment by mayuresh-savargaonkar** [comment]
Was there a fix to this?

**Comment by paulwuertz** [comment]
I also saw the same issue. Following the guide leaves me with an empty ui sub-page.

![image](https://github.com/user-attachments/assets/ec68cbc8-8b00-444a-a9b4-9dfa1182202b)

While executing `./user_workspace/everest-core/build/run-scripts/nodered-sil.sh` I also get the warning about

> notsup Unsupported engine for node-red-node-ui-table@0.4.4: wanted: {"node":">=16"} (current: {"node":"14.19.3","npm":"6.14.17"})

![image](https://github.com/user-attachments/assets/6d9f937d-1066-46f2-9955-3bb92555a69e)

 ENV NODE_VERSION=14.19.3 is set in the [node-red container](nodered/node-red:2.2.3-minimal)

**Comment by paulwuertz** [comment]
Related to https://github.com/EVerest/everest-core/pull/895.
Adding RUN npm install node-red-node-ui-table**@0.4.3** on the build Dockerfile at everest-core/build/dist/share/everest/docker/Dockerfile made the dashboard work ^^
