### ISSUE TITLE
EvseV2G: The ChargingStatusRes lost ReceiptRequired parameter when EIM Identification

### ISSUE THREAD

**Issue by SeanHsu0318** [EVerest/everest-core#946]
### Describe the bug
In ISO 15118-2:2014 rule V2G2-691, the ChargingStatusRes shall always include parameter "ReceiptRequired" with value "false" for EIM Identification. 

Currently, the "ChargingStatusRes" include "ReceiptRequired" when payment type is contract only :
https://github.com/EVerest/everest-core/blob/1a162cc5648da6d33bea75ed82eb14e742a83a2b/modules/EvseV2G/iso_server.cpp#L1494

### EVerest Domain
evserest-core

### Affected EVerest Module
EvseV2G

### To Reproduce
Start charging with ISO 15118 EIM

### Anything else?
No response

**Comment by SebaLukas** [comment]
Hi :) Thx for discovering this bug. I created a fix already.

**Comment by SebaLukas** [comment]
The fix is merged
